services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./.env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=myuserpassword
      - MYSQL_DATABASE=mydb
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=YOUR_USERNAME
      - RABBITMQ_DEFAULT_PASS=YOUR_PASSWORD
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    container_name: django-web
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
